#
# run on push and every Thursday 8:42 am
#
#
name: build docker images

on:
  push:
    branches: master

  schedule:
    cron: '42 8 * * 4'

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build images
        run: ./bin/build.sh
